Check there's enough available disk space before starting the collector

diff --git a/ds-collector/ds-collector b/ds-collector/ds-collector
--- a/ds-collector/ds-collector
+++ b/ds-collector/ds-collector
@@ -142,6 +142,12 @@ list_cassandra_nodes() {
   for ip in ${cassandraNodes} ; do
     ip -4 a | grep -q $ip && { echo >&2 "The ds-collector script cannot be executed from a Cassandra/DSE node. Please execute the script from a jumpbox/bastion server that has access to all nodes to the data-center/cluster."; exit 1; }
   done
+
+  # more accurate disk space check
+  node_count="${#cassandraNodes[@]}"
+  required_basedir_space="$((${node_count} * 500000))"
+  [ $(df --output=avail "$baseDir"  | grep -v Avail) -ge ${required_basedir_space} ] ||  { echo >&2 "A diagnostic collection of ${node_count} nodes requires at least $((${required_basedir_space} / 1000000))GB free at $baseDir"; exit 1; }
+
   # also grab the cluster name
   cmd="nodetool $nodetoolHost -p $jmxPort $nodetoolCredentials describecluster"
   clusterName=$(node_connect "$cmd" | grep Name | awk '{print $2}')
@@ -225,12 +231,18 @@ node_connect_ssh() {
 
 bastion_checks() {
   # pre-conditions
+  mkdir -p $baseDir
+  if [ "$?" != "0" ]; then
+    echo "we couldn't make our working directory: $baseDir...exiting"
+    exit 2
+  fi
   command -v xxd >/dev/null 2>&1 || { echo >&2 "xxd needs to be installed"; exit 1; }
   [ "$use_docker" = "true" ] || [ "$use_k8s" = "true" ] || command -v ssh >/dev/null 2>&1 || { echo >&2 "ssh needs to be installed"; exit 1; }
   [ "$use_docker" = "true" ] || [ "$use_k8s" = "true" ] || command -v scp >/dev/null 2>&1 || { echo >&2 "scp needs to be installed"; exit 1; }
   [ "$use_docker" = "true" ] || [ "$use_k8s" = "true" ] || ! [ -n "$sshPassword" ] || command -v sshpass >/dev/null 2>&1 || { echo >&2 "sshpass needs to be installed"; exit 1; }
   ! [ "$use_docker" = "true" ] || command -v docker >/dev/null 2>&1 || { echo >&2 "docker needs to be installed"; exit 1; }
   ! [ "$use_k8s" = "true" ] || command -v kubectl >/dev/null 2>&1 || { echo >&2 "kubectl needs to be installed"; exit 1; }
+  [ $(df --output=avail "$baseDir"  | grep -v Avail) -ge 1000000 ] ||  { echo >&2 "There must be at least 1GB free at $baseDir"; exit 1; }
   # revert the prometheus jarfile from text back to jarfile
   [[ -f "$prometheus" ]] || { ( LC_ALL=C tr -cd 0-9a-fA-F < "${prometheus/jar/txt}" | xxd -r -p > "$prometheus" ); }
 }
@@ -239,6 +251,7 @@ node_checks() {
   [[ -f "$baseDir/$prometheus" ]] || { echo >&2 "$baseDir/$prometheus must exist"; exit 1; }
   [[ -x "$baseDir/$dstat" ]] || { echo >&2 "$baseDir/$dstat must exist"; exit 1; }
   [[ -x "$baseDir/collect-info" ]] || { echo >&2 "$baseDir/collect-info must exist"; exit 1; }
+  [ $(df --output=avail "$baseDir"  | grep -v Avail) -ge 1000000 ] ||  { echo >&2 "There must be at least 1GB free at $baseDir"; exit 1; }
 }
 
 read_host_name() {
@@ -779,11 +792,6 @@ read_config() {
 # shellcheck disable=SC2086,SC1001
 # Called from the primary machine
 get_infos() {
-  mkdir -p $baseDir
-  if [ "$?" != "0" ]; then
-    echo "we couldn't make our working directory: $baseDir...exiting"
-    exit 2
-  fi
   if [ $hostFile ]; then
     while read -u10 hostName; do
       if [[ "$hostName" != \#* ]] && [ "$hostName" ]; then
@@ -792,8 +800,8 @@ get_infos() {
     done 10< $hostFile
   elif [[ ${runOnSingleNode} != "true" ]] && [[ "$hostName" != \#* ]] && [ "$hostName" ]; then
     list_cassandra_nodes
-    for host in ${cassandraNodes}
-    do
+    # XXX – can be optimised to do all nodes in a rack in parallel
+    for host in ${cassandraNodes} ; do
       hostName=$host
       if [[ "$hostName" != \#* ]] && [ "$hostName" ]; then
         get_info
