enabling alternate location for dse.yaml

diff --git a/ds-collector/ds-collector b/ds-collector/ds-collector
--- a/ds-collector/ds-collector
+++ b/ds-collector/ds-collector
@@ -661,12 +661,12 @@ collect_info_setup() {
         echo "DSE install: package directories successfully found. Proceeding..."
         dse_root_dir="/etc/dse/"
         dse_bin_dir="/usr/bin/"
-        dse_conf_dir="/etc/dse/"
+        dse_conf_dir="${dseConfigHome:-/etc/dse/}"
         configHome="/etc/dse/cassandra"
     elif [ -d "$dse_root_dir" ] && [ -d "$dse_root_dir/resources/cassandra/conf" ] && [ -d "$dse_root_dir/resources/dse/conf" ]; then
         echo "DSE install: tarball directories successfully found. Proceeding..."
         dse_bin_dir="$dse_root_dir/bin/"
-        dse_conf_dir="$dse_root_dir/resources/dse/conf/"
+        dse_conf_dir="${dseConfigHome:-$dse_root_dir/resources/dse/conf/}"
         configHome="$dse_root_dir/resources/cassandra/conf"
     else
         echo "DSE install: no package or tarball directories found, or no tarball directory specified."
@@ -675,6 +675,7 @@ collect_info_setup() {
     [[ -d "$dse_bin_dir" ]] || { echo "dse_bin_dir points to a non-existing directory $dse_bin_dir"; exit 1; }
     [[ -d "$dse_conf_dir" ]] || { echo "dse_conf_dir points to a non-existing directory $dse_conf_dir"; exit 1; }
     [[ -d "$configHome" ]] || { echo "configHome points to a non-existing directory $configHome"; exit 1; }
+    [[ -f "${dse_conf_dir}/dse.yaml" ]] || { echo "dse.yaml not found in $dse_conf_dir - configure dseConfigHome?"; exit 1; }
 
     # Versions to determine if nodesync available
     dse_version="$($dse_bin_dir/dse -v)"
