squash me

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,44 +48,43 @@ jobs:
     - name: Spin up cluster
       if: ${{ success() }}
       run: |
-          tlp-cluster init DS DSI-58 "Integration tests for the DS diagnostic toolkit"
-          tlp-cluster up --auto-approve
-          tlp-cluster use 3.11.7
-          tlp-cluster install
-          tlp-cluster start
-#         success=0
-#         attempts=1
-#         while [ $success -eq  0 ] && [ $attempts -lt 5 ];
-#         do
-#             echo "Installing packages (attempt $attempts)"
-#             tlp-cluster install > install.log 2>&1 || echo "meh... install phase seem to have failed"
-#             grep "try rerunning the install" install.log > /dev/null 2>&1
-#             success=$? # 0 means we found errors in the logs, so we need to try again
-#             attempts=$((attempts+1))
-#         done
-#
-#         if [ $success -eq  0 ]
-#         then
-#             echo "tlp-cluster install failed after $attempts retries. Exiting (╯°□°)╯︵ ┻━┻"
-#             exit 1
-#         fi
-#
-#         success=0
-#         attempts=1
-#         while [ $success -eq  0 ]  && [ $attempts -lt 5 ];
-#         do
-#             echo "Starting Cassandra (attempt $attempts)"
-#             tlp-cluster start > start.log 2>&1 || echo "meh... start phase seem to have failed"
-#             tail -3 start.log | grep "Non zero response returned" > /dev/null 2>&1
-#             success=$?
-#             attempts=$((attempts+1))
-#         done
-#
-#         if [ $success -eq 0 ]
-#         then
-#             echo "tlp-cluster start failed after $attempts retries. Exiting (╯°□°)╯︵ ┻━┻"
-#             exit 1
-#         fi
+          echo "Initializing AWS cluster..."
+          tlp-cluster init DS DSI-58 "Integration tests for the DS diagnostic toolkit" > /dev/null 2>&1
+          echo "Spinning up EC2 instances..."
+          tlp-cluster up --auto-approve > /dev/null 2>&1
+          tlp-cluster use 3.11.7 > /dev/null 2>&1
+          success=0
+          attempts=1
+          while [ $success -eq  0 ] && [ $attempts -lt 5 ];
+          do
+              echo "Installing packages (attempt $attempts)..."
+              tlp-cluster install > install.log 2>&1 || echo "meh... install phase seem to have failed"
+              grep "try rerunning the install" install.log > /dev/null 2>&1
+              success=$? # 0 means we found errors in the logs, so we need to try again
+              attempts=$((attempts+1))
+          done
+ 
+          if [ $success -eq  0 ]
+          then
+              echo "tlp-cluster install failed after $attempts retries. Exiting (╯°□°)╯︵ ┻━┻"
+              exit 1
+          fi
+ 
+          success=0
+          attempts=1
+          while [ $success -eq  0 ]  && [ $attempts -lt 5 ];
+          do
+              echo "Starting Cassandra (attempt $attempts)..."
+              tlp-cluster start > start.log 2>&1 || echo "meh... start phase seem to have failed"
+              success=$?
+              attempts=$((attempts+1))
+          done
+ 
+          if [ $success -eq 0 ]
+          then
+              echo "tlp-cluster start failed after $attempts retries. Exiting (╯°□°)╯︵ ┻━┻"
+              exit 1
+          fi
     - name: Run diagnostics collection
       if: ${{ success() }}
       run: |
