Fix docker issues Only encrypt unencrypted artifacts

diff --git a/.github/workflows/oss_unencrypted.yml b/.github/workflows/oss_unencrypted.yml
--- a/.github/workflows/oss_unencrypted.yml
+++ b/.github/workflows/oss_unencrypted.yml
@@ -32,15 +32,19 @@ jobs:
           sudo dpkg -i tlp-cluster.deb
           mkdir -p /home/runner/.tlp-cluster/profiles/default
 
-          sudo apt-get install     apt-transport-https     ca-certificates     curl     gnupg-agent     software-properties-common
+          sudo apt-get install     apt-transport-https     ca-certificates     curl     gnupg-agent     software-properties-common -y
           curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
           sudo add-apt-repository    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
           sudo apt-get update
-          sudo apt-get install docker-ce docker-ce-cli containerd.io
+          sudo apt-get install docker-ce docker-ce-cli containerd.io -y
           sudo usermod -aG docker ${USER}
           sudo apt-get install awscli
+          # No clue why we need to pull these manually now...
+          docker pull hashicorp/terraform:0.11.14
+          docker pull thelastpickle/pssh:1.0
+          docker pull thelastpickle/cassandra-build:1.0
     - name: Configure tlp-cluster
       if: ${{ success() }}
       env:
@@ -61,14 +65,14 @@ jobs:
       if: ${{ success() }}
       run: |
           echo "Initializing AWS cluster..."
-          tlp-cluster init DS DSI-58 "Integration tests for the DS diagnostic toolkit" -c 3 --instance m5.large > /dev/null 2>&1
+          timeout --foreground 120 tlp-cluster init DS DSI-58 "Integration tests for the DS diagnostic toolkit" -c 3 --instance m5.large > /dev/null 2>&1
           echo "Spinning up EC2 instances..."
-          tlp-cluster up --auto-approve > /dev/null 2>&1
-          tlp-cluster use 3.11.7 --config "cluster_name:diag_integration_tests" > /dev/null 2>&1
+          timeout --foreground 120 tlp-cluster up --auto-approve > /dev/null 2>&1
+          timeout --foreground 180 tlp-cluster use 3.11.7 --config "cluster_name:diag_integration_tests" > /dev/null 2>&1
           echo "Installing packages..."
-          tlp-cluster install > install.log 2>&1 || echo "meh... install phase seem to have failed"
+          timeout --foreground 600 tlp-cluster install > install.log 2>&1 || echo "meh... install phase seem to have failed"
           echo "Starting Cassandra..."
-          tlp-cluster start > start.log 2>&1 || echo "meh... start phase seem to have failed"
+          timeout --foreground 600 tlp-cluster start > start.log 2>&1 || echo "meh... start phase seem to have failed"
  
     - name: Run diagnostics collection
       if: ${{ success() }}
@@ -113,6 +117,6 @@ jobs:
       if: ${{ always() }}
       run: |
           echo "Terminating instances, please be patient..."
-          tlp-cluster down --auto-approve > down.log 2>&1
+          timeout --foreground 600 tlp-cluster down --auto-approve > down.log 2>&1
           tail -10 down.log
 
